### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [dimtass/DSP-Cpp-filters#4]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (under the [Audio](https://github.com/forart/HyMPS#-1) -> [Libraries section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md)), can you please set licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/dimtass/DSP-Cpp-filters/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/dimtass/DSP-Cpp-filters/?label=LICENSE)

...maybe it's a GH setup issue ?

Thanks in advance.

**Comment by dimtass** [comment]
Hi Marco, I can't access my GitHub for a few weeks as I'm on vacation, but
generally all my content is MIT

I'll add a file when I'm back.

Regards,
Dimitris

**Comment by dimtass** [comment]
@forart Hi Marco, I've pushed the license and I hope that fixes any issues you have. Btw, excuse the delay I've just return back to civilization :D

**Comment by MarcoRavich** [comment]
Welcome back @dimtass, as you can see now license badge works:
https://github.com/forart/HyMPS/blob/main/AudioDSPs.md

Thanks !
